# Generated by Django 4.0.3 on 2022-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_album_amount_remove_album_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.CharField(default='song.opus', max_length=100),
            preserve_default=False,
        ),
    ]
