# Generated by Django 4.0.3 on 2022-04-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_playlist_songs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='date',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='minutes',
        ),
    ]
